// Mapeo de equipos del Mundial 2026: códigos ISO + nombre legible
export const EQUIPOS_INFO = {
  'MEXICO':           { iso: 'mx', nombre: 'México' },
  'SOUTH AFRICA':     { iso: 'za', nombre: 'Sudáfrica' },
  'KOREA':            { iso: 'kr', nombre: 'Corea del Sur' },
  'REP. CHECA':       { iso: 'cz', nombre: 'Rep. Checa' },
  'CANADA':           { iso: 'ca', nombre: 'Canadá' },
  'BOSNIA-HERZEGOVINA': { iso: 'ba', nombre: 'Bosnia-Herzegovina' },
  'QATAR':            { iso: 'qa', nombre: 'Catar' },
  'SUIZA':            { iso: 'ch', nombre: 'Suiza' },
  'BRASIL':           { iso: 'br', nombre: 'Brasil' },
  'MARRUECOS':        { iso: 'ma', nombre: 'Marruecos' },
  'HAITI':            { iso: 'ht', nombre: 'Haití' },
  'ESCOCIA':          { iso: 'gb-sct', nombre: 'Escocia' },
  'USA':              { iso: 'us', nombre: 'Estados Unidos' },
  'PARAGUAY':         { iso: 'py', nombre: 'Paraguay' },
  'AUSTRALIA':        { iso: 'au', nombre: 'Australia' },
  'TUQUIA':           { iso: 'tr', nombre: 'Turquía' },
  'ALEMANIA':         { iso: 'de', nombre: 'Alemania' },
  'CURACAO':          { iso: 'cw', nombre: 'Curazao' },
  'COSTA DE MARFIL':  { iso: 'ci', nombre: 'Costa de Marfil' },
  'ECUADOR':          { iso: 'ec', nombre: 'Ecuador' },
  'PAISES BAJOS':     { iso: 'nl', nombre: 'Países Bajos' },
  'JAPON':            { iso: 'jp', nombre: 'Japón' },
  'SUECIA':           { iso: 'se', nombre: 'Suecia' },
  'TUNEZ':            { iso: 'tn', nombre: 'Túnez' },
  'BELGICA':          { iso: 'be', nombre: 'Bélgica' },
  'EGIPTO':           { iso: 'eg', nombre: 'Egipto' },
  'IRAN':             { iso: 'ir', nombre: 'Irán' },
  'NUEVA ZELANDA':    { iso: 'nz', nombre: 'Nueva Zelanda' },
  'ESPAÑA':           { iso: 'es', nombre: 'España' },
  'CABO VERDE':       { iso: 'cv', nombre: 'Cabo Verde' },
  'ARABIA SAUDITA':   { iso: 'sa', nombre: 'Arabia Saudita' },
  'URUGUAY':          { iso: 'uy', nombre: 'Uruguay' },
  'FRANCIA':          { iso: 'fr', nombre: 'Francia' },
  'SENEGAL':          { iso: 'sn', nombre: 'Senegal' },
  'IRAQ':             { iso: 'iq', nombre: 'Iraq' },
  'NORUEGA':          { iso: 'no', nombre: 'Noruega' },
  'ARGENTINA':        { iso: 'ar', nombre: 'Argentina' },
  'ARGELIA':          { iso: 'dz', nombre: 'Argelia' },
  'AUSTRIA':          { iso: 'at', nombre: 'Austria' },
  'JORDANIA':         { iso: 'jo', nombre: 'Jordania' },
  'PORTUGAL':         { iso: 'pt', nombre: 'Portugal' },
  'CONGO':            { iso: 'cd', nombre: 'RD Congo' },
  'UZBEKISTAN':       { iso: 'uz', nombre: 'Uzbekistán' },
  'COLOMBIA':         { iso: 'co', nombre: 'Colombia' },
  'INGLATERRA':       { iso: 'gb-eng', nombre: 'Inglaterra' },
  'CROACIA':          { iso: 'hr', nombre: 'Croacia' },
  'GHANA':            { iso: 'gh', nombre: 'Ghana' },
  'PANAMA':           { iso: 'pa', nombre: 'Panamá' },
  'FWC 2026':         { iso: 'FWC', nombre: 'FIFA World Cup 2026' },
  'FIFA HISTORY':     { iso: 'HIS', nombre: 'FIFA History' },
  'COCA COLA':        { iso: 'CC', nombre: 'Coca-Cola Stars' },
};

// Helper: obtener info de un equipo (con fallback seguro)
export const getEquipoInfo = (equipo) => {
  return EQUIPOS_INFO[equipo] || { 
    iso: '?', 
    nombre: equipo 
  };
};